#!/bin/sh
echo "ProxyChains-3.1 (http://proxychains.sf.net)"

usage() {

	echo "	usage:"
	echo "		$0 [h] [f config-file] <prog> [args]"
	exit
}

if [ $# = 0 ] ; then
	usage
fi

if [ $1 = "-h" ]; then
	usage
fi

if [ "$1" = "-f" ]; then
	export PROXYCHAINS_CONF_FILE=$2;
	shift;
	shift;
fi

export LD_PRELOAD=libproxychains.so.3
exec "$@"
